TLO-BASE-URL = "https://capitol.texas.gov/"
BILL-TEXT-BASE = "tlodocs/{lege_session}/billtext/html/{chamber}{bill_num}"
FISCAL-NOTE-BASE = "tlodocs/{lege_session}/fiscalnotes/html/{chamber}{bill_num}"

[CHAMBER-URLS]
MEMBER-LIST = "Members/Members.aspx?Chamber={}"

[MEMBER-URLS]
BILL-LIST = "reports/report.aspx?LegSess={}&ID=author&Code={}"
BILL-LOOKUP = "BillLookup/History.aspx?LegSess={}&Bill={}"

[BILL-DETAIL-URLS]  # These suffixes go after the BILL-TEXT-BASE and FISCAL-NOTE-BASE
    BillText.Introduced = "I.htm"
    BillText.Engrossed = "E.htm"
    BillText.HouseReport = "H.htm"
    BillText.SenateReport = "S.htm"
    BillText.Enrolled = "F.htm"
    FiscalNote.Introduced = "I.htm"
    FiscalNote.HouseReport =  "H.htm"
    FiscalNote.Engrossed = "E.htm"