MAIN-TLO-URL = "https://capitol.texas.gov/"

[CHAMBER-URLS]
MEMBER-LIST = "Members/Members.aspx?Chamber={}"

[MEMBER-URLS]
BILL-LIST = "reports/report.aspx?LegSess={}&ID=author&Code={}"
BILL-LOOKUP = "BillLookup/History.aspx?LegSess={}&Bill={}"

[BILL-DETAIL-URLS]  # These URLS are used to get the bill information. 3 vars are used: Legislative Session, Chamber, and Bill Number
    BillText.Introduced = "tlodocs/{}/billtext/html/{}{}I.htm"
    BillText.Engrossed = "tlodocs/{}/billtext/html/{}{}E.htm"
    BillText.HouseReport = "tlodocs/{}/billtext/html/{}{}H.htm"
    BillText.SenateReport = "tlodocs/{}/billtext/html/{}{}S.htm"
    BillText.Enrolled = "tlodocs/{}/billtext/html/{}{}F.htm"
    FiscalNote.Introduced = "tlodocs/{}/fiscalnotes/html/{}{}I.htm"
    FiscalNote.HouseReport =  "tlodocs/{}/fiscalnotes/html/{}{}H.htm"
    FiscalNote.Engrossed = "tlodocs/{}/fiscalnotes/html/{}{}E.htm"